name: Validate Notes Keys

on:
  pull_request:
    paths:
      - 'android_beta/*.yml'
      - 'android_release/*.yml'
      - 'beta/*.yml'
      - 'esr/*.yml'
      - 'release/*.yml'
      - 'tools/validate_notes_keys.py'
      - '.github/workflows/validate-keys.yml'
  push:
    branches:
      - master
    paths:
      - 'android_beta/*.yml'
      - 'android_release/*.yml'
      - 'beta/*.yml'
      - 'esr/*.yml'
      - 'release/*.yml'
      - 'tools/validate_notes_keys.py'
      - '.github/workflows/validate-keys.yml'

permissions:
  contents: read

jobs:
  validate:
    name: Validate `notes` keys
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Validate YAML notes keys
        run: |
          python tools/validate_notes_keys.py
